language: python
python:
- '3.6'
env:
  global:
  - PYTHONPATH="."
script: python celery_bundle/test/test_bundle.py
deploy:
  provider: pypi
  user: maxpowel
  password:
    secure: MQyXuQvUW/h9H7An1Xhv/Uz+ocJiJCWx+jLADmHECsajvz6cvBSt31hkS+Mc6zSTiocjwbLBMFotn9mfNxSbW0J1/eqGZBODWMKO+i1q5O31pTqs/ehspZuJJj0y9OO+ty4dAeZb4lpHlUkzHz8pYPukLHkmX9SVYEcd8Cmt7uHCKYpMFx74ScH8kx+CSARDZfSBOlIl+ugSBZkCih38o8gQQ2Kh+uHD4MReuHOnOFR9j74bCOsIv7DNI2dI52sHbNeTf11yflP7N3+1SyHTHP6q87itjMImYbTZXbfq4qSziU0deFgfUknAl0LuU4A/mhNGtG7g+/lrRp+Sj0cQ6DybFYSXsTWEZxEZ2yuplu4rV0vj+dYjifodEoAgse+ixQ6FA/dgZ8DvG4UzvQdvgeHvgtgdz1S+UlRGp1Z5ZIyA9h7uwHxUupOheyaPisMICXOOCC+scoMMN1KgvKYiQOOtR0KSRIE/tvW1GqWqXQwqsRRUrzBCJo4Aj/y50NdOIoVRE4EBFy8I33Cjc5a1albWhclhOU0fupX7xaGbteVOXLBCtyQYq7dQT/+mvdfGxS3zZd7D8/uJ/vGqdbOEUv4OBhYPikzev/H7utHZFOwA+gpv6luzr/DTQ4LXnJjMzz+lhCBxaxaGfa5TLi+xlb7EfoYvoPI9dWLAX70wPNU=
  distributions: bdist_wheel
  on:
    tags: true
